# Generated by Django 4.0.3 on 2022-03-03 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainPage',
        ),
    ]
