# Generated by Django 4.0.2 on 2022-03-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_items_category_items_image_items_name_items_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
