# Generated by Django 4.0.3 on 2022-03-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_category_names_sizes_alter_items_options_items_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='stock',
            field=models.IntegerField(verbose_name='STOCK'),
        ),
    ]
