# Generated by Django 4.0.3 on 2022-03-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_items_description'),
        ('mainapp', '0005_items_description_alter_items_stock'),
    ]

    operations = [
    ]
