# Generated by Django 4.0.3 on 2022-03-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_merge_20220316_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='description',
        ),
    ]
